# Generated by Django 5.2.5 on 2025-09-03 18:15

import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, help_text='کد ملی', max_length=10, validators=[users.validators.IranianNationalIdValidator]),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, help_text='دریافت اطلاعیه\u200cها از طریق پیامک'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_spent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[users.validators.IranianPhoneValidator]),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='نام آدرس (مثل: خانه، محل کار)', max_length=50)),
                ('address_type', models.CharField(choices=[('home', 'خانه'), ('work', 'محل کار'), ('other', 'سایر')], default='home', max_length=10)),
                ('province', models.CharField(help_text='استان', max_length=50)),
                ('city', models.CharField(help_text='شهر', max_length=50)),
                ('district', models.CharField(blank=True, help_text='منطقه/محله', max_length=50)),
                ('street', models.CharField(help_text='خیابان و کوچه', max_length=200)),
                ('alley', models.CharField(blank=True, help_text='کوچه/پلاک', max_length=100)),
                ('building_number', models.CharField(blank=True, help_text='شماره ساختمان', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='واحد', max_length=10)),
                ('postal_code', models.CharField(help_text='کد پستی', max_length=10, validators=[users.validators.IranianPostalCodeValidator])),
                ('recipient_name', models.CharField(help_text='نام گیرنده', max_length=100)),
                ('recipient_phone', models.CharField(help_text='شماره تماس گیرنده', max_length=11, validators=[users.validators.IranianPhoneValidator])),
                ('description', models.TextField(blank=True, help_text='توضیحات تکمیلی (نشانی دقیق)')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس\u200cهای کاربران',
                'db_table': 'user_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
