# Generated by Django 5.2.5 on 2025-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='assets/images/default.jpg', help_text='تصویر محصول', null=True, upload_to='product_images/'),
        ),
    ]
