# Generated by Django 5.2.5 on 2025-09-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended',
            field=models.BooleanField(default=False, help_text='آیا این محصول پیشنهادی است؟'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='محصولات مرتبط یا پیشنهادی برای نمایش', related_name='related_to', to='products.product'),
        ),
    ]
